extends Node

signal BUL_create_bulletin
signal BUL_destroy_bulletin
signal BUL_destroy_all_bulletins

signal PLA_freeze_player
signal PLA_unfreeze_player

signal STA_change_stage
var is_transitioning := false

signal MUS_play_music

signal SFX_play_sfx
signal SFX_play_dynamic_sfx

signal HUD_hide_hud
signal HUD_show_hud

signal INV_ask_update_inventory
signal INV_inventory_updated
signal INV_switch_two_inventory_item_indexes
signal INV_delete_item_by_index
signal INV_try_to_pickup_item
